### ISSUE TITLE
[Umbrella Issue] overcurried 2.0

### ISSUE THREAD

**Issue by ENvironmentSet** [ENvironmentSet/overcurried#13]
# Todos

- [ ] Better code view ([ref](https://blog.outsider.ne.kr/?page=5))
- [ ] Quote style fix
- [ ] List style fix
- [ ] TIL page + source(personal wikipedia service) ([ref](https://lionhairdino.github.io))
- [ ] #14
